#The following functions are used to create a custom object that stores and 
#caches a matrix and its inverse. 
#makeCacheMatrix is the first function, and it creates a unique matrix.


makeCacheMatrix <- function(x = matrix()) {
    i <- NULL
  set <- function(y) {
          x <<- y
          i <<- NULL
  }
  get <- function() x
  setinverse <- function(inverse) i <<- inverse
  getinverse <- function() i
  list(set = set,
       get = get,
       setinverse = setinverse,
       getinverse = getinverse)
}

#This function computes the inverse of the particular "matrix" generated by makeCacheMatrix. 
# If indeed the inverse has now been calculated cacheSolve must retrieve it from the cache.


cacheSolve <- function(x, ...) {
  i <- x$getinverse()
  if (!is.null(i)) {
          message("getting cached data")
          return(i)
  }
  data <- x$get()
  i <- solve(data, ...)
  x$setinverse(i)
  i
}



